### ISSUE TITLE
Säkerhetsbugg i ditt api !

### ISSUE THREAD

**Issue by Linkaan** [itggot-joel-eriksson/ITG-Infoskarm#1]
Jag stötte på något jag tror är en bugg. Jag lyckades extrahera din auth key för västrafiks API (f081adfd-**xxxx**-**xxxx**-**xxxx**-**xxxxxxxxx**eaf)

Om du vill kan jag skicka hur man återskapar buggen i ett mail. Föresten verkar det här som ett riktigt häftigt projekt :)

**Comment by theswedishdev** [comment]
Ett mail med detaljer för hur du lyckades extrahera auth key för Västtrafiks API hade verkligen uppskattats, kommer därefter att försöka patcha detta **ASAP**.

Tackar för hjälpen så länge.

**Comment by theswedishdev** [comment]
Buggen berodde på den felrapportering som används i PHP, _auth key_ kunde extraheras om _id-parametern_ innehöll mellanslag. Detta åtgärdades genom att stänga av felrapporteringen samt genom att kolla efter eventuella mellanslag i _id-parametern_.
